(define (problem PROBLEM_CARGO)
    (:domain DOMAIN_CARGO)
    (:objects PLANE1 PLANE2 BCN SFO P1 P2)
    (:init
        (plane PLANE1)
        (plane PLANE2)
        (airport BCN)
        (airport SFO)
        (package P1)
        (package P2)
        (empty PLANE1)
        (empty PLANE2)
        (at PLANE1 BCN)
        (at PLANE2 SFO)
        (at P1 BCN)
        (at P2 SFO)
    )
    (:goal
        (and 
            (at P1 SFO)
            (at P2 BCN)
        )
    )
)